#!/bin/bash -e

# https://github.com/toddmowen/version-check-git-hook

base="origin/master"
version_file="version.sbt"

if ! git show-ref --quiet "$base"
then
	echo ".git/hooks/pre-push is misconfigured: base '$base' does not exist" >&2
	exit 1
fi

if ! git show "$base:$version_file" >/dev/null 2>&1
then
	echo ".git/hooks/pre-push is misconfigured: file '$version_file' does not exist in '$base'" >&2
	exit 1
fi

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
	if [[ "$local_sha" != $z40 ]]
	then
		# merely check whether the version file has been modified (a simple but naive test)
		if git diff --quiet "$local_sha" "$base" -- ":/$version_file"
		then
			echo "warning: '$local_ref' includes no update to '$version_file' (relative to base '$base')" >&2
			read -p'Really push? [y/N]: ' answer </dev/tty
			[[ "$answer" == "y" || "$answer" == "Y" ]] || exit 1
		fi
	fi
done

exit 0
